config/routes.rb
Rails.application.routes.draw do
  root "chart#index"
  resources :finances
  resources :products, only: %i[index new create]
  get "chart/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/finance.rb
class Finance < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chart_controller.rb
class ChartController < ApplicationController
  def index
    @finances = Finance.group_by_day(:date).sum(:amount)
  end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: %i[ show edit update destroy ]

  # GET /finances or /finances.json
  def index
    @finances = Finance.all
  end

  # GET /finances/1 or /finances/1.json
  def show
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances or /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to finance_url(@finance), notice: "Finance was successfully created." }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1 or /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to finance_url(@finance), notice: "Finance was successfully updated." }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1 or /finances/1.json
  def destroy
    @finance.destroy!

    respond_to do |format|
      format.html { redirect_to finances_url, notice: "Finance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def finance_params
      params.require(:finance).permit(:date, :amount)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @dd = {"hoge": 50, "fuga": 30, "foo": 70, "bar": 10}
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  private

  def product_params
    params.require(:product).permit(%i[amount price])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/chart/index.html.erb
<h1>Finance Chart</h1>
<%= line_chart @finances %>
<%= link_to 'Finances', finances_path %>
<br>
<%= link_to 'Products', products_path %>

app/views/finances/_finance.html.erb
<div id="<%= dom_id finance %>">
  <p>
    <strong>Date:</strong>
    <%= finance.date %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= finance.amount %>
  </p>

</div>

app/views/finances/_form.html.erb
<%= form_with(model: finance) do |form| %>
  <% if finance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
        <% finance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/finances/edit.html.erb
<h1>Editing finance</h1>

<%= render "form", finance: @finance %>

<br>

<div>
  <%= link_to "Show this finance", @finance %> |
  <%= link_to "Back to finances", finances_path %>
</div>

app/views/finances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Finances</h1>

<div id="finances">
  <% @finances.each do |finance| %>
    <%= render finance %>
    <%= link_to "Show this finance", finance %>
  <% end %>
</div>

<P><%= link_to "New finance", new_finance_path %></P>
<P><%= link_to "Back to Chart", chart_index_path %></P>

app/views/finances/new.html.erb
<h1>New finance</h1>

<%= render "form", finance: @finance %>

<br>

<div>
  <%= link_to "Back to finances", finances_path %>
</div>

app/views/finances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @finance %>

<div>
  <p><%= link_to "New finance", new_finance_path %> </p>
  <%= link_to "Edit this finance", edit_finance_path(@finance) %> |
  <%= link_to "Back to finances", finances_path %>

  <%= button_to "Destroy this finance", @finance, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceChart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Amount:</strong>
    <%= product.amount %>

    <strong>Price:</strong>
    <%= product.price %>
  </p>

</div>

app/views/products/index.html.erb
<h1>Products</h1>

<%= line_chart @products.group(:price).sum(:amount) %>


<% @products.each do |product| %>
  <%= render product %>
<% end %>

<%= pie_chart @dd %>

<%= link_to "New Product", new_product_path %>
<br>
<%= link_to "return to TOP", root_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to Products", products_path %>
</div>